version: '3'

services:
  redis:
    container_name: my_sweet_redis
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    expose:
      - 6379

  mongo:
    container_name: my_sweet_mongo
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017

  # app:
  #   container_name: my_sweet_container
  #   build: .
  #   ports:
  #     - ${APP_PORT}:${APP_PORT}
  #   command: 'yarn start'
  #   depends_on:
  #     - mongo
  #     - redis
