version: "3"

services:
  # app:
  #   container_name: my_sweet_url
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   command: yarn dev
  #   # volumes:
  #   #   - ./data:/data/db
  #   links:
  #     - mongo
  redis:
    container_name: my_sweet_redis
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379

  mongo:
    container_name: my_sweet_mongo
    image: mongo
    restart: always
    ports:
      - ${DB_PORT}:27017
