version: "3"

services:
  app:
    container_name: mysweeturl
    build: .
    ports:
      - "3000:3000"
    command: yarn dev
    # volumes:
    #   - ./data:/data/db
    links:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"
